<?php

namespace Database\Seeders;

use App\Models\Vehicle;
use App\Models\User;
use App\Models\Dealer;
use Illuminate\Database\Seeder;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        // Find sellers or create them
        $seller1 = User::where('email', 'seller@test.com')->first();
        if (!$seller1) {
            $seller1 = User::create([
                'name' => 'Premium Auto Dealer',
                'email' => 'seller@test.com',
                'password' => bcrypt('password'),
                'user_type' => 'seller',
                'country' => 'DE',
                'is_verified' => true,
            ]);
        }

        $seller2 = User::where('email', 'seller2@test.com')->first();
        if (!$seller2) {
            $seller2 = User::create([
                'name' => 'Elite Motors',
                'email' => 'seller2@test.com',
                'password' => bcrypt('password'),
                'user_type' => 'seller',
                'country' => 'DE',
                'is_verified' => true,
            ]);
        }

        $vehicles = [
            // BMW Vehicles
            [
                'make' => 'BMW',
                'model' => '320d xDrive Touring',
                'year' => 2020,
                'vin' => 'WBA1234567890001',
                'mileage' => 45000,
                'fuel_type' => 'diesel',
                'transmission' => 'automatic',
                'body_type' => 'wagon',
                'color' => 'Mineral White',
                'doors' => 5,
                'seats' => 5,
                'engine_size' => 1995,
                'power_hp' => 190,
                'price' => 28500.00,
                'currency' => 'EUR',
                'location_city' => 'Munich',
                'location_country' => 'DE',
                'description' => 'Excellent condition BMW 320d xDrive Touring with full service history. Perfect for families or business use.',
                'status' => 'active',
                'seller_id' => $seller1->id,
            ],
            [
                'make' => 'BMW',
                'model' => 'X5 M50d',
                'year' => 2021,
                'vin' => 'WBA1234567890002',
                'mileage' => 32000,
                'fuel_type' => 'diesel',
                'transmission' => 'automatic',
                'body_type' => 'suv',
                'color' => 'Sophisto Grey',
                'doors' => 5,
                'seats' => 7,
                'engine_size' => 2993,
                'power_hp' => 400,
                'price' => 62900.00,
                'currency' => 'EUR',
                'location_city' => 'Munich',
                'location_country' => 'DE',
                'description' => 'Powerful BMW X5 M50d with M Sport package. Full options, 7 seats.',
                'status' => 'active',
                'seller_id' => $seller1->id,
            ],

            // Mercedes-Benz Vehicles
            [
                'make' => 'Mercedes-Benz',
                'model' => 'A 200',
                'year' => 2022,
                'vin' => 'WDB1234567890001',
                'mileage' => 15000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'body_type' => 'hatchback',
                'color' => 'Digital White',
                'doors' => 5,
                'seats' => 5,
                'engine_size' => 1332,
                'power_hp' => 163,
                'price' => 32500.00,
                'currency' => 'EUR',
                'location_city' => 'Stuttgart',
                'location_country' => 'DE',
                'description' => 'Almost new Mercedes A 200 with MBUX system and premium package.',
                'status' => 'active',
                'seller_id' => $seller2->id,
            ],
            [
                'make' => 'Mercedes-Benz',
                'model' => 'E 220 d',
                'year' => 2021,
                'vin' => 'WDB1234567890002',
                'mileage' => 38000,
                'fuel_type' => 'diesel',
                'transmission' => 'automatic',
                'body_type' => 'sedan',
                'color' => 'Obsidian Black',
                'doors' => 4,
                'seats' => 5,
                'engine_size' => 1950,
                'power_hp' => 194,
                'price' => 45900.00,
                'currency' => 'EUR',
                'location_city' => 'Stuttgart',
                'location_country' => 'DE',
                'description' => 'Mercedes E-Class with AMG Line, panoramic roof, and premium sound system.',
                'status' => 'active',
                'seller_id' => $seller2->id,
            ],

            // Audi Vehicles
            [
                'make' => 'Audi',
                'model' => 'A4 Avant',
                'year' => 2020,
                'vin' => 'WAU1234567890001',
                'mileage' => 52000,
                'fuel_type' => 'diesel',
                'transmission' => 'automatic',
                'body_type' => 'wagon',
                'color' => 'Glacier White',
                'doors' => 5,
                'seats' => 5,
                'engine_size' => 1968,
                'power_hp' => 204,
                'price' => 33900.00,
                'currency' => 'EUR',
                'location_city' => 'Ingolstadt',
                'location_country' => 'DE',
                'description' => 'Audi A4 Avant S line with virtual cockpit and matrix LED headlights.',
                'status' => 'active',
                'seller_id' => $seller1->id,
            ],
            [
                'make' => 'Audi',
                'model' => 'Q5 45 TFSI',
                'year' => 2022,
                'vin' => 'WAU1234567890002',
                'mileage' => 18000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'body_type' => 'suv',
                'color' => 'Navarra Blue',
                'doors' => 5,
                'seats' => 5,
                'engine_size' => 1984,
                'power_hp' => 249,
                'price' => 52500.00,
                'currency' => 'EUR',
                'location_city' => 'Ingolstadt',
                'location_country' => 'DE',
                'description' => 'Audi Q5 with S line package, air suspension, and full LED lighting.',
                'status' => 'active',
                'seller_id' => $seller2->id,
            ],

            // Volkswagen Vehicles
            [
                'make' => 'Volkswagen',
                'model' => 'Golf GTI',
                'year' => 2021,
                'vin' => 'WVW1234567890001',
                'mileage' => 28000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'body_type' => 'hatchback',
                'color' => 'Tornado Red',
                'doors' => 5,
                'seats' => 5,
                'engine_size' => 1984,
                'power_hp' => 245,
                'price' => 34900.00,
                'currency' => 'EUR',
                'location_city' => 'Wolfsburg',
                'location_country' => 'DE',
                'description' => 'VW Golf GTI Mk8 with Performance Pack. Dynamic Chassis Control included.',
                'status' => 'active',
                'seller_id' => $seller1->id,
            ],
            [
                'make' => 'Volkswagen',
                'model' => 'Tiguan R-Line',
                'year' => 2020,
                'vin' => 'WVW1234567890002',
                'mileage' => 42000,
                'fuel_type' => 'diesel',
                'transmission' => 'automatic',
                'body_type' => 'suv',
                'color' => 'Pyrite Silver',
                'doors' => 5,
                'seats' => 5,
                'engine_size' => 1968,
                'power_hp' => 150,
                'price' => 29900.00,
                'currency' => 'EUR',
                'location_city' => 'Wolfsburg',
                'location_country' => 'DE',
                'description' => 'VW Tiguan R-Line with digital cockpit and travel assist.',
                'status' => 'active',
                'seller_id' => $seller2->id,
            ],

            // Porsche
            [
                'make' => 'Porsche',
                'model' => '911 Carrera',
                'year' => 2021,
                'vin' => 'WP01234567890001',
                'mileage' => 12000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'body_type' => 'coupe',
                'color' => 'Guards Red',
                'doors' => 2,
                'seats' => 4,
                'engine_size' => 2981,
                'power_hp' => 385,
                'price' => 98500.00,
                'currency' => 'EUR',
                'location_city' => 'Stuttgart',
                'location_country' => 'DE',
                'description' => 'Iconic Porsche 911 Carrera with Sport Chrono package. Perfect condition.',
                'status' => 'active',
                'seller_id' => $seller1->id,
            ],

            // Tesla
            [
                'make' => 'Tesla',
                'model' => 'Model 3 Long Range',
                'year' => 2022,
                'vin' => '5YJ1234567890001',
                'mileage' => 8000,
                'fuel_type' => 'electric',
                'transmission' => 'automatic',
                'body_type' => 'sedan',
                'color' => 'Pearl White',
                'doors' => 4,
                'seats' => 5,
                'engine_size' => 0,
                'power_hp' => 346,
                'price' => 52900.00,
                'currency' => 'EUR',
                'location_city' => 'Berlin',
                'location_country' => 'DE',
                'description' => 'Tesla Model 3 Long Range AWD with Autopilot and premium interior.',
                'status' => 'active',
                'seller_id' => $seller2->id,
            ],

            // Ford
            [
                'make' => 'Ford',
                'model' => 'Mustang Mach-E',
                'year' => 2023,
                'vin' => '1FA1234567890001',
                'mileage' => 5000,
                'fuel_type' => 'electric',
                'transmission' => 'automatic',
                'body_type' => 'suv',
                'color' => 'Rapid Red',
                'doors' => 5,
                'seats' => 5,
                'engine_size' => 0,
                'power_hp' => 294,
                'price' => 48900.00,
                'currency' => 'EUR',
                'location_city' => 'Cologne',
                'location_country' => 'DE',
                'description' => 'Ford Mustang Mach-E electric SUV with extended range battery and BlueCruise.',
                'status' => 'active',
                'seller_id' => $seller1->id,
            ],

            // Opel
            [
                'make' => 'Opel',
                'model' => 'Astra Sports Tourer',
                'year' => 2020,
                'vin' => 'W0L1234567890001',
                'mileage' => 58000,
                'fuel_type' => 'diesel',
                'transmission' => 'manual',
                'body_type' => 'wagon',
                'color' => 'Moonstone Grey',
                'doors' => 5,
                'seats' => 5,
                'engine_size' => 1598,
                'power_hp' => 136,
                'price' => 18900.00,
                'currency' => 'EUR',
                'location_city' => 'Rüsselsheim',
                'location_country' => 'DE',
                'description' => 'Practical Opel Astra Sports Tourer with large cargo space and excellent fuel economy.',
                'status' => 'active',
                'seller_id' => $seller2->id,
            ],

            // Renault
            [
                'make' => 'Renault',
                'model' => 'Megane E-Tech',
                'year' => 2023,
                'vin' => 'VF11234567890001',
                'mileage' => 3000,
                'fuel_type' => 'electric',
                'transmission' => 'automatic',
                'body_type' => 'hatchback',
                'color' => 'Solaris Orange',
                'doors' => 5,
                'seats' => 5,
                'engine_size' => 0,
                'power_hp' => 220,
                'price' => 39900.00,
                'currency' => 'EUR',
                'location_city' => 'Frankfurt',
                'location_country' => 'DE',
                'description' => 'Brand new Renault Megane E-Tech electric with Google built-in and OpenR display.',
                'status' => 'active',
                'seller_id' => $seller1->id,
            ],

            // Peugeot
            [
                'make' => 'Peugeot',
                'model' => '3008 GT',
                'year' => 2021,
                'vin' => 'VF31234567890001',
                'mileage' => 35000,
                'fuel_type' => 'diesel',
                'transmission' => 'automatic',
                'body_type' => 'suv',
                'color' => 'Vertigo Blue',
                'doors' => 5,
                'seats' => 5,
                'engine_size' => 1997,
                'power_hp' => 177,
                'price' => 28500.00,
                'currency' => 'EUR',
                'location_city' => 'Hamburg',
                'location_country' => 'DE',
                'description' => 'Peugeot 3008 GT with i-Cockpit, panoramic sunroof, and Focal premium audio.',
                'status' => 'active',
                'seller_id' => $seller2->id,
            ],

            // Volvo
            [
                'make' => 'Volvo',
                'model' => 'XC60 Recharge',
                'year' => 2022,
                'vin' => 'YV11234567890001',
                'mileage' => 22000,
                'fuel_type' => 'hybrid',
                'transmission' => 'automatic',
                'body_type' => 'suv',
                'color' => 'Crystal White',
                'doors' => 5,
                'seats' => 5,
                'engine_size' => 1969,
                'power_hp' => 455,
                'price' => 54900.00,
                'currency' => 'EUR',
                'location_city' => 'Düsseldorf',
                'location_country' => 'DE',
                'description' => 'Volvo XC60 T8 Recharge plug-in hybrid with Pilot Assist and Harman Kardon sound.',
                'status' => 'active',
                'seller_id' => $seller1->id,
            ],

            // Mazda
            [
                'make' => 'Mazda',
                'model' => 'CX-5 Skyactiv-G',
                'year' => 2021,
                'vin' => 'JM11234567890001',
                'mileage' => 31000,
                'fuel_type' => 'petrol',
                'transmission' => 'automatic',
                'body_type' => 'suv',
                'color' => 'Soul Red Crystal',
                'doors' => 5,
                'seats' => 5,
                'engine_size' => 1998,
                'power_hp' => 165,
                'price' => 27900.00,
                'currency' => 'EUR',
                'location_city' => 'Berlin',
                'location_country' => 'DE',
                'description' => 'Mazda CX-5 with premium Bose audio, leather interior, and i-Activsense safety.',
                'status' => 'active',
                'seller_id' => $seller2->id,
            ],

            // Skoda
            [
                'make' => 'Skoda',
                'model' => 'Octavia Combi RS',
                'year' => 2020,
                'vin' => 'TMB1234567890001',
                'mileage' => 48000,
                'fuel_type' => 'diesel',
                'transmission' => 'automatic',
                'body_type' => 'wagon',
                'color' => 'Race Blue',
                'doors' => 5,
                'seats' => 5,
                'engine_size' => 1968,
                'power_hp' => 200,
                'price' => 26900.00,
                'currency' => 'EUR',
                'location_city' => 'Leipzig',
                'location_country' => 'DE',
                'description' => 'Skoda Octavia Combi RS with DSG transmission, virtual cockpit, and sports suspension.',
                'status' => 'active',
                'seller_id' => $seller1->id,
            ],

            // Reserved/Sold examples
            [
                'make' => 'BMW',
                'model' => '530e iPerformance',
                'year' => 2019,
                'vin' => 'WBA1234567890003',
                'mileage' => 65000,
                'fuel_type' => 'hybrid',
                'transmission' => 'automatic',
                'body_type' => 'sedan',
                'color' => 'Black Sapphire',
                'doors' => 4,
                'seats' => 5,
                'engine_size' => 1998,
                'power_hp' => 252,
                'price' => 34500.00,
                'currency' => 'EUR',
                'location_city' => 'Munich',
                'location_country' => 'DE',
                'description' => 'BMW 530e plug-in hybrid with luxury package and gesture control.',
                'status' => 'reserved',
                'seller_id' => $seller1->id,
            ],

            [
                'make' => 'Audi',
                'model' => 'A6 Allroad',
                'year' => 2018,
                'vin' => 'WAU1234567890003',
                'mileage' => 85000,
                'fuel_type' => 'diesel',
                'transmission' => 'automatic',
                'body_type' => 'wagon',
                'color' => 'Daytona Grey',
                'doors' => 5,
                'seats' => 5,
                'engine_size' => 2967,
                'power_hp' => 272,
                'price' => 38900.00,
                'currency' => 'EUR',
                'location_city' => 'Ingolstadt',
                'location_country' => 'DE',
                'description' => 'Audi A6 Allroad quattro with air suspension, panoramic roof, and Bang & Olufsen.',
                'status' => 'sold',
                'seller_id' => $seller2->id,
            ],
        ];

        foreach ($vehicles as $vehicleData) {
            Vehicle::create($vehicleData);
        }

        $this->command->info('Created ' . count($vehicles) . ' test vehicles!');
    }
}
