// API Services Exports
export { authService } from './auth'
export { vehicleService } from './vehicles'
export { transactionService } from './transactions'
export { paymentService } from './payments'
export { contractService } from './contracts'
export { invoiceService } from './invoices'
export { messageService } from './messages'
export { notificationService } from './notifications'
export { verificationService } from './verification'
export { default as kycService } from './kyc'
export { default as userService } from './user'
export { default as apiClient } from './client'

// New services
export { default as bankAccountService } from './bank-accounts'
export { default as orderService } from './orders'
export { default as reviewService } from './reviews'
export { default as disputeService } from './disputes'
export { default as legalService } from './legal'
export { default as cookieService } from './cookies'
export { default as gdprService } from './gdpr'
export { default as localeService } from './locale'

// Export dealer service functions individually for compatibility
export * from './dealers'

// Re-export types
export type { RegisterData, LoginData, AuthResponse } from './auth'
export type { Vehicle, VehicleFilters, VehicleListResponse, CreateVehicleData } from './vehicles'
export type { Transaction, BankTransferDetails, CreateTransactionData } from './transactions'
export type { Message, Conversation, ConversationDetail, SendMessageData } from './messages'
export type { BankAccount, CreateBankAccountData } from './bank-accounts'
export type { CreateOrderData, PaymentInstructions } from './orders'
export type { Review, CreateReviewData } from './reviews'
export type { Dispute, DisputeResponse, CreateDisputeData } from './disputes'
export type { LegalDocument, UserConsent, RecordConsentData } from './legal'
export type { CookiePreferences, CookieConsent } from './cookies'
export type { PrivacySettings } from './gdpr'
export type { LocaleInfo } from './locale'
